// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type BenchmarkKtype string

const (
	BenchmarkKtypeHigh BenchmarkKtype = "high"
)

func (e *BenchmarkKtype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BenchmarkKtype(s)
	case string:
		*e = BenchmarkKtype(s)
	default:
		return fmt.Errorf("unsupported scan type for BenchmarkKtype: %T", src)
	}
	return nil
}

type NullBenchmarkKtype struct {
	BenchmarkKtype BenchmarkKtype `json:"benchmark_ktype"`
	Valid          bool           `json:"valid"` // Valid is true if BenchmarkKtype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBenchmarkKtype) Scan(value interface{}) error {
	if value == nil {
		ns.BenchmarkKtype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BenchmarkKtype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBenchmarkKtype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BenchmarkKtype), nil
}

type BenchmarkResult struct {
	CandidateID      uuid.UUID      `json:"candidate_id"`
	JobDescriptionID uuid.UUID      `json:"job_description_id"`
	BenchmarkType    BenchmarkKtype `json:"benchmark_type"`
}

type BenchmarkResultDetail struct {
	ID               int32          `json:"id"`
	CandidateID      uuid.UUID      `json:"candidate_id"`
	JobDescriptionID uuid.UUID      `json:"job_description_id"`
	BenchmarkType    BenchmarkKtype `json:"benchmark_type"`
	Result           string         `json:"result"`
}

type Candidate struct {
	ID              uuid.UUID      `json:"id"`
	AppliedPosition string         `json:"applied_position"`
	Email           string         `json:"email"`
	CvInfo          string         `json:"cv_info"`
	CvPath          string         `json:"cv_path"`
	OriginalCvName  sql.NullString `json:"original_cv_name"`
	FileHash        string         `json:"file_hash"`
	PlainText       string         `json:"plain_text"`
	Embedding       interface{}    `json:"embedding"`
	CreatedAt       time.Time      `json:"created_at"`
}

type JobDescription struct {
	ID        uuid.UUID   `json:"id"`
	PlainText string      `json:"plain_text"`
	JobTitle  string      `json:"job_title"`
	JdPath    string      `json:"jd_path"`
	FileHash  string      `json:"file_hash"`
	JdInfo    string      `json:"jd_info"`
	Embedding interface{} `json:"embedding"`
}

type User struct {
	ID             int32  `json:"id"`
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
	FullName       string `json:"full_name"`
}
