// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetCandidate(ctx context.Context) ([]GetCandidateRow, error)
	GetResults(ctx context.Context) ([]string, error)
	GetUserByUsername(ctx context.Context, email string) (GetUserByUsernameRow, error)
}

var _ Querier = (*Queries)(nil)
